<a href="https://colab.research.google.com/github/Sakibapon/BRAC/blob/master/NumpyFinalVersion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#What is Numpy?


Numpy is a python library provides you with an array data structure that holds some benefits over Python lists, such as: being more compact, faster access in reading and writing items, being more convenient and more efficient.

In other words, NumPy is a Python library that is the core library for scientific computing in Python. It contains a collection of tools and techniques that can be used to solve on a computer mathematical models of problems in Science and Engineering. One of these tools is a high-performance multidimensional array object that is a powerful data structure for efficient computation of arrays and matrices.

We will create numpy arrays using python and numpy library.
Numpy array comes in 2 flavours : 
1. 1D Vector
2. 2D Matrix



#Creating a normal List

> 




In [ ]:
my_list=[1,2,3]
my_list 


[1, 2, 3]

#Casting a normal python list into a numpy array

NumPy library follows an import convention: when you import this library, you have to make sure that you import it as **np**. By doing this, you’ll make sure that other Pythonistas understand your code more easily.

In [ ]:
import numpy as np
a=np.array(my_list)


In [ ]:
my_mat=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]
np.array(my_mat)


array([list([1, 2, 3, 2]), list([4, 5, 6, 6]), list([7, 8, 9, 7]),
       list([10, 11, 12.8]), list([1, 2, 4, 8]), list([1, 2, 45, 8])],
      dtype=object)

#Numpy own genatation method

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#Numpy also provides many functions to create arrays:

In [ ]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((4,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [ ]:
np.eye(5) #identitity matrix(2d square matrix)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#creating arrays of random numbers
np.random.rand(5) #uniform distribution from 0 to 1

array([0.21291522, 0.33153834, 0.10763181, 0.66616025, 0.57622581])

In [ ]:
#creating arrays of random numbers
np.random.rand(5,5) # 2D uniform distribute from 0 to 1

array([[0.77012301, 0.26355333, 0.52170039, 0.46224365, 0.46815306],
       [0.99990464, 0.530256  , 0.7591817 , 0.04866451, 0.0957894 ],
       [0.47025353, 0.32650206, 0.30898887, 0.09178975, 0.21586981],
       [0.25771434, 0.9752487 , 0.58573739, 0.4458637 , 0.4025186 ],
       [0.71015059, 0.59938424, 0.62259241, 0.70765912, 0.38812001]])

In [ ]:
#creating arrays of random numbers
np.random.randn(4) # standard normal distribution range from -infinty to infinity

array([ 1.74588294,  0.869566  , -0.12160965,  0.17811526])

In [ ]:
#creating arrays of random numbers
np.random.randint(1,100,20)    

array([ 9, 95, 91, 86, 66, 97, 42, 69, 10,  6, 30, 88, 32, 61, 60, 50, 84,
       49,  9, 42])

In [ ]:
#gives you 6 numbers randomly from 0-(10-1)
x1 = np.random.randint(10, size=6)
x1

array([8, 5, 3, 2, 9, 3])

In [ ]:
x2 = np.random.randint(10, size=(3,4,3))
print(x2)
print(x2.shape)
print(f"Dimensiion = {x2.ndim}")

[[[7 2 7]
  [4 1 1]
  [2 1 5]
  [1 1 8]]

 [[6 0 3]
  [9 3 9]
  [1 0 9]
  [6 0 7]]

 [[5 6 3]
  [1 0 3]
  [4 6 6]
  [9 5 5]]]
(3, 4, 3)
Dimensiion = 3


In [ ]:
#creating max and min value in array
my_arr=np.array([1,-3,4,5,3,4,56,7,-34])
print(my_arr.min())
print(my_arr.max())

-34
56


In [ ]:
#returning index number max and min value in array
print(my_arr.argmin())
print(my_arr.argmax())

8
6


In [ ]:
#how to find the shape of vector?
my_arr.shape

(9,)

In [ ]:
#how to reshape vector?
my_arr.reshape(3,3)

array([[  1,  -3,   4],
       [  5,   3,   4],
       [ 56,   7, -34]])

In [ ]:
#how to know  what the data type value we have in array ?

my_arr.dtype

dtype('int64')

In [ ]:
#append
import numpy as np
new_arr=np.arange(1,11)
print(new_arr)
new_arr= np.append(new_arr,100)
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10]
[  1   2   3   4   5   6   7   8   9  10 100]


In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
b= np.array([[400],[800]])
print(b)
newarr = np.append(a, b,axis=1 )
print(newarr)

[[1 2 3]
 [4 5 6]]
[[400]
 [800]]
[  1   2   3   4   5   6 400 800]


In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b= np.array([[400],[800]])
newarr = np.append(a, b)
print(newarr)

[[  1   2   3 400]
 [  4   5   6 800]]


In [ ]:
#insert
a= np.array([1 , 2, 3])
print( a) 
new_array= np.insert(a,0, 1000)
print(new_array)

[1 2 3]
[1000    1    2    3]


In [ ]:
#delete
import numpy as np
a = np.array([[1,2,3],[4,5,6],[10,20,30]])

print(a)
narr = np.delete(a,1,axis=1)
print(narr)

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]]
[[ 1  3]
 [ 4  6]
 [10 30]]


In [ ]:
#finding the index of a value in the array usin where() method
a = np.array([1 , 2 ,3, 5 ,4 ,5])
print(np.where(a==5))

(array([3, 5]),)


#Numpy Indexing and Selection


In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a[1,2]

6

In [ ]:
a[:,1:2]


array([[ 2],
       [ 5],
       [20]])

In [ ]:
a[:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
#conditional selection
b = a > 2  #take an array and combine with conditional operate to get a boolean values/arrays
print(b)

[[False False  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
#return only those elements those were true using bollean array
a[b] 

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
#in one go!!
a[a>2]

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1 = np.array([[1,2,3],[4,5,6],[9,10,11]])
print(a1)

[[ 1  2  3]
 [ 4  5  6]
 [ 9 10 11]]


In [ ]:

a1[a1<=2]=0
a1[a1>2]=1
a1

array([[0, 0, 1],
       [1, 1, 1],
       [1, 1, 1]])

#NumPy Operations

In [ ]:
import numpy as np
arr=np.arange(0,11)
arr2=np.arange(0,11)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#addition
arr+arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
#substraction
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#multiplication
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
arr/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
#scaling an array
arr+100
#to the power
#squareroot
#sin
#log
#max/min

https://numpy.org/doc/stable/reference/ufuncs.html#:~:text=That%20is%2C%20a%20ufunc%20is,implemented%20in%20compiled%20C%20code.


SyntaxError: ignored